name: Run build and test for Task 4

on: 
  push: 
    branches:
      - master
    paths: 
      - Task4/src/**
      - .github/workflows/builds.yml
jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Task4/src/

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build